import React from 'react';
import { ToolGuide } from './ToolGuide';

export const AIPromptGuide = () => {
    return (
        <ToolGuide
            title="The Future of Color Generation"
            description="How AI is revolutionizing the way designers create color systems. From semantic understanding to emotional mapping."
        >
            <div className="grid md:grid-cols-2 gap-12 items-start mb-20">
                <div>
                    <h3 className="text-2xl font-bold text-gray-900 mb-4">Why use AI for Color Palettes?</h3>
                    <p className="text-gray-600 mb-6 leading-relaxed">
                        Traditional color generators rely on mathematical algorithms (like complementary or triadic harmony). While effective, they lack <strong>context</strong>. An algorithm doesn't know that "Forest at Midnight" should feel mysterious and cool, or that "Spicy Food Brand" needs energetic reds and oranges.
                    </p>
                    <p className="text-gray-600 leading-relaxed">
                        Our AI Color Prompt Lab uses Large Language Models (LLMs) to understand the <em>semantic meaning</em> behind your prompt. It maps emotions, objects, and cultural contexts to specific hex codes, creating palettes that "feel" right, not just look mathematically correct.
                    </p>
                </div>
                <div className="bg-gradient-to-br from-indigo-50 to-blue-50 p-8 rounded-3xl border border-indigo-100">
                    <h4 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                        How to write great prompts
                    </h4>
                    <ul className="space-y-3">
                        <li className="flex gap-3 text-sm font-medium text-gray-700">
                            <span className="w-1.5 h-1.5 rounded-full bg-indigo-600 mt-2 shrink-0"></span>
                            <strong>Be descriptive:</strong> Instead of "Blue", try "Deep oceanic blue with a hint of teal".
                        </li>
                        <li className="flex gap-3 text-sm font-medium text-gray-700">
                            <span className="w-1.5 h-1.5 rounded-full bg-indigo-600 mt-2 shrink-0"></span>
                            <strong>Include mood:</strong> Words like "Melancholic", "Energetic", or "Serene" help the AI tune saturation.
                        </li>
                        <li className="flex gap-3 text-sm font-medium text-gray-700">
                            <span className="w-1.5 h-1.5 rounded-full bg-indigo-600 mt-2 shrink-0"></span>
                            <strong>Mention context:</strong> Adding "for a banking app" or "for a kid's toy" completely changes the output.
                        </li>
                    </ul>
                </div>
            </div>

            <h3 className="text-3xl font-bold text-gray-900 mb-8">Frequently Asked Questions</h3>
            <div className="space-y-6 mb-16">
                <div className="border border-gray-200 rounded-2xl p-6 hover:shadow-md transition-shadow">
                    <h4 className="font-bold text-gray-900 mb-2">Can I use these colors commercially?</h4>
                    <p className="text-gray-600 text-sm">Yes! All palettes generated by our AI are royalty-free and can be used in personal or commercial projects without attribution.</p>
                </div>
                <div className="border border-gray-200 rounded-2xl p-6 hover:shadow-md transition-shadow">
                    <h4 className="font-bold text-gray-900 mb-2">How does the "Context" setting work?</h4>
                    <p className="text-gray-600 text-sm">
                        The context selector tunes the AI's constraints. <strong>UI/UX</strong> mode ensures high contrast for text legibility. <strong>Art</strong> mode prioritizes harmony and unique blends. <strong>Print</strong> mode avoids neon RGB values that can't be reproduced in CMYK.
                    </p>
                </div>
                <div className="border border-gray-200 rounded-2xl p-6 hover:shadow-md transition-shadow">
                    <h4 className="font-bold text-gray-900 mb-2">Why does it sometimes ignore my locked colors?</h4>
                    <p className="text-gray-600 text-sm">
                        While we instruct the AI to respect locked colors, strict adherence can sometimes break the harmony it's trying to build. We are constantly finetuning the model to prioritize your constraints.
                    </p>
                </div>
            </div>
        </ToolGuide>
    );
};
